"""ManifestLoader — boots the agent framework from YAML manifests.

Responsibilities:
- Load domain.yaml, agent_manifest.yaml, workflow YAML files
- Resolve system_prompt_ref to file content
- Load domain context_files (standards, architecture docs)
- Resolve tool pack declarations → register built-in adapters in ToolExecutor
- Build step_configs dict ready for CompositionEngine.execute_dag()
- Wire AgentRunner + CompositionEngine into a runnable engine
"""

from __future__ import annotations

import logging
import os
import warnings
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)


# B5 — Architect v2 feature flag (audit §8 Phase 2d).
# v2 is the default — catalog-driven, knows about stage_defaults / capability
# bindings / gate+feedback loop patterns. Set GENTCORE_ARCHITECT_V2=0 (or
# false/no/off) to force v1 for debugging parity.
_ARCHITECT_V2_ENV = "GENTCORE_ARCHITECT_V2"
_ARCHITECT_V1_ID = "_genesis/AgentArchitectAgent/v1"
_ARCHITECT_V2_ID = "_genesis/AgentArchitectAgent/v2"


def _architect_v2_enabled() -> bool:
    raw = os.environ.get(_ARCHITECT_V2_ENV, "").strip().lower()
    if not raw:  # unset → default ON
        return True
    return raw not in ("0", "false", "no", "off")


_STRICT_MANIFESTS_ENV = "GENTCORE_STRICT_MANIFESTS"


def _strict_manifests_enabled() -> bool:
    """When True, manifest validation failures raise instead of warning.

    Default OFF preserves backward compatibility — existing dev domains
    with looser manifests keep loading. Set ``GENTCORE_STRICT_MANIFESTS=1``
    in CI / production startup so invalid manifests fail-fast at boot
    rather than producing partially-broken agents at runtime.
    """
    return str(os.environ.get(_STRICT_MANIFESTS_ENV, "")).strip().lower() in (
        "1", "true", "yes", "on",
    )


def _emit_manifest_validation_failure(kind: str, path: Any, exc: Exception) -> None:
    """Single emit-or-raise dispatcher for manifest validation failures.

    ``kind`` is one of ``domain``, ``agent``, ``workflow``. The strict-mode
    flag turns warnings into ``ValueError``s with ``path`` and the underlying
    exception preserved as the ``__cause__``.
    """
    msg = f"{kind.capitalize()} manifest validation failed for {path}: {exc}"
    if _strict_manifests_enabled():
        raise ValueError(msg) from exc
    warnings.warn(msg, stacklevel=3)


def build_memory_store(domain_root: Path) -> Any | None:
    """Build the Tier 4 FileMemoryStore for a domain.

    Resolution:
      1. `GENTCORE_MEMORY_DIR` env var — lets multiple domains share a
         store (e.g. cross-domain genesis memory).
      2. `<domain_root>/.gentcore/memory` — default, naturally scoped
         per-domain so history accumulates across re-runs.

    Returns None if the memory_store module can't be imported — the
    rest of the runtime degrades gracefully (AgentRunner no-ops when
    `memory_store is None`).
    """
    try:
        from harness.core.memory_store import FileMemoryStore
    except Exception as exc:
        logger.debug("Memory store unavailable, running without memory: %s", exc)
        return None
    override = os.environ.get("GENTCORE_MEMORY_DIR")
    if override:
        base = Path(override).expanduser()
        if base.name != "memory":
            base = base / ".gentcore" / "memory"
    else:
        base = domain_root / ".gentcore" / "memory"
    logger.debug("FileMemoryStore wired at %s", base)
    return FileMemoryStore(base_dir=base)


def _build_preload_item(
    preload_name: str,
    domain_root: str | Path | None = None,
) -> dict[str, Any] | None:
    """Build a context_items entry for a named preload source.

    Supported sources:
      * `tool_pack_catalog` — reads every YAML under `agent_tools/packs/`
        and returns a flattened catalog the ToolDiscovery agent can consume
        without iterative file_read calls.
      * `shadow_gentcore_builtin_tools` — reads APPROVED_TOOLS from
        harness/tools/builtin.py so discovery knows the native tool surface.
      * `domain_context_docs` — all files under `{domain_root}/context/*.md`
        flattened into one blob. Used by ContextEngineerAgent so it can
        generate new context docs from existing ones in one shot.
      * `best_practices_overlay` — Tier 1.5 always-injected overlay read
        from `{domain_root}/context/best_practices.md`. Generated by
        BestPracticeAdvisorAgent; complements standards.md without
        replacing it. No-op when the file is absent.

    Returns None if the source is unknown or produces no content.
    """
    if preload_name == "tool_pack_catalog":
        return _preload_tool_pack_catalog()
    if preload_name == "shadow_gentcore_builtin_tools":
        return _preload_builtin_tools_inventory()
    if preload_name == "domain_context_docs":
        if not domain_root:
            return None
        return _preload_domain_context_docs(Path(domain_root))
    if preload_name == "shared_stage_catalog":
        return _preload_shared_stage_catalog()
    if preload_name == "capabilities_config":
        return _preload_capabilities_config()
    if preload_name == "known_mcp_servers":
        return _preload_known_mcp_servers()
    if preload_name == "tool_security_policy":
        return _preload_tool_security_policy()
    if preload_name == "project_file_tree":
        if not domain_root:
            return None
        return _preload_project_file_tree(Path(domain_root))
    if preload_name == "domain_evolution_signals":
        if not domain_root:
            return None
        return _preload_domain_evolution_signals(Path(domain_root))
    if preload_name == "best_practices_overlay":
        if not domain_root:
            return None
        return _preload_best_practices_overlay(Path(domain_root))
    if preload_name == "best_practice_library":
        if not domain_root:
            return None
        return _preload_best_practice_library(Path(domain_root))
    logger.warning("Unknown context.preload source: %r", preload_name)
    return None


def _preload_tool_pack_catalog() -> dict[str, Any] | None:
    """Flatten every tool pack YAML into a single indexed catalog blob."""
    try:
        import agent_tools
        packs_root = Path(agent_tools.__file__).parent / "packs"
    except Exception as exc:
        logger.warning("agent_tools not importable for preload: %s", exc)
        return None
    if not packs_root.exists():
        return None

    parts: list[str] = ["# Available Tool Packs (pre-loaded catalog)\n"]
    parts.append(
        "Each pack declares one or more tools. Prefer these over fabricating "
        "new ones. To include a pack, reference its `id:` (e.g. "
        "`toolpack://core/filesystem`).\n\n"
    )
    for pack_yaml in sorted(packs_root.rglob("*.yaml")):
        try:
            data = yaml.safe_load(pack_yaml.read_text(encoding="utf-8")) or {}
        except Exception:
            continue
        pack_id = data.get("id") or f"toolpack://{pack_yaml.relative_to(packs_root).with_suffix('')}"
        tools = data.get("tools") or []
        tool_names = [t.get("name") if isinstance(t, dict) else str(t) for t in tools]
        desc = (data.get("description") or "").strip().replace("\n", " ")[:200]
        parts.append(f"## `{pack_id}`\n")
        if desc:
            parts.append(f"{desc}\n")
        if tool_names:
            parts.append(f"tools: {', '.join(filter(None, tool_names))}\n")
        parts.append("\n")
    content = "".join(parts)
    return {
        "source": "preload:tool_pack_catalog",
        "content": content,
        "priority": 5,
    }


def _preload_builtin_tools_inventory() -> dict[str, Any] | None:
    """Inventory of framework-native tools registered by harness/tools/builtin.py."""
    try:
        from harness.tools import builtin as _builtin
    except Exception:
        return None
    names = getattr(_builtin, "APPROVED_TOOLS", None)
    if not names:
        # Fallback: list public callables that look like tool helpers
        names = [n for n in dir(_builtin) if not n.startswith("_")]
    lines = ["# Framework Built-in Tools (harness/tools/builtin.py)\n\n"]
    lines.extend(f"- `{n}`\n" for n in sorted(set(str(n) for n in names)))
    return {
        "source": "preload:shadow_gentcore_builtin_tools",
        "content": "".join(lines),
        "priority": 5,
    }


def _preload_shared_stage_catalog() -> dict[str, Any] | None:
    """Flatten every `agents/_shared/*/v*/agent_manifest.yaml` into a stage catalog.

    Used by AgentArchitectAgent/v2 so it doesn't need to iteratively file_read
    20+ stage-agent manifests during composition. Each entry carries
    `id` (agent id path), `name`, `stage` tag, and `purpose` (from description).
    """
    framework_root = Path(__file__).resolve().parent.parent.parent
    shared_root = framework_root / "agents" / "_shared"
    if not shared_root.exists():
        return None

    entries: list[dict[str, Any]] = []
    for mf_path in sorted(shared_root.glob("*/v*/agent_manifest.yaml")):
        try:
            data = yaml.safe_load(mf_path.read_text(encoding="utf-8")) or {}
        except Exception:
            continue
        aid = data.get("id") or f"_shared/{mf_path.relative_to(shared_root).parent}"
        name = mf_path.parent.parent.name
        meta = data.get("metadata") or {}
        tags = meta.get("tags") or []
        stage = meta.get("stage") or data.get("stage") or ""
        if not stage:
            # Heuristic: first uppercase tag is the stage (matches existing catalog convention)
            for tag in tags if isinstance(tags, list) else []:
                if isinstance(tag, str) and tag and tag[0].isupper():
                    stage = tag
                    break
        purpose = (data.get("description") or "").strip().split("\n", 1)[0][:200]
        entries.append({
            "id": aid,
            "name": name,
            "stage": stage,
            "purpose": purpose,
        })

    if not entries:
        return None
    lines = ["# Shared Stage Catalog (pre-loaded)\n"]
    lines.append("Reuse these agents before synthesizing new ones. Columns: id | stage | name — purpose.\n\n")
    for e in entries:
        lines.append(f"- `{e['id']}` | stage=`{e['stage'] or '(unset)'}` | {e['name']} — {e['purpose']}\n")
    return {
        "source": "preload:shared_stage_catalog",
        "content": "".join(lines),
        "priority": 5,
    }


def _preload_capabilities_config() -> dict[str, Any] | None:
    """Read framework `config/capabilities.yaml` verbatim.

    Used by AgentArchitectAgent/v2 to map stage → capabilities → tool packs.
    """
    framework_root = Path(__file__).resolve().parent.parent.parent
    cfg_path = framework_root / "config" / "capabilities.yaml"
    if not cfg_path.exists():
        return None
    try:
        body = cfg_path.read_text(encoding="utf-8")
    except Exception:
        return None
    content = (
        "# Capability Map (pre-loaded from config/capabilities.yaml)\n\n"
        "```yaml\n"
        f"{body}\n"
        "```\n"
    )
    return {
        "source": "preload:capabilities_config",
        "content": content,
        "priority": 5,
    }


def _preload_known_mcp_servers() -> dict[str, Any] | None:
    """Read `config/known_mcp_servers.yaml` so ToolSynthesizer can prefer
    wrapping existing MCP servers over synthesizing new packs."""
    framework_root = Path(__file__).resolve().parent.parent.parent
    cfg_path = framework_root / "config" / "known_mcp_servers.yaml"
    if not cfg_path.exists():
        return None
    try:
        body = cfg_path.read_text(encoding="utf-8")
    except Exception:
        return None
    return {
        "source": "preload:known_mcp_servers",
        "content": (
            "# Known Public MCP Servers (pre-loaded)\n\n"
            "Prefer wrapping one of these over synthesizing a new pack when "
            "the capability + credentials match. Each entry lists repo, "
            "purpose, required credentials, and suitability_tags.\n\n"
            "```yaml\n"
            f"{body}\n"
            "```\n"
        ),
        "priority": 5,
    }


def _preload_tool_security_policy() -> dict[str, Any] | None:
    """Read `config/tool_security.yaml` so ToolSynthesizer knows what patterns
    to avoid (hardcoded secrets, unsafe URL templates, unscoped shell, etc.)."""
    framework_root = Path(__file__).resolve().parent.parent.parent
    cfg_path = framework_root / "config" / "tool_security.yaml"
    if not cfg_path.exists():
        return None
    try:
        body = cfg_path.read_text(encoding="utf-8")
    except Exception:
        return None
    return {
        "source": "preload:tool_security_policy",
        "content": (
            "# Tool Security Policy (pre-loaded — enforced at gate)\n\n"
            "Every pack you emit must satisfy these rules or the gate blocks "
            "the workflow. Default-deny for credential exposure, unsafe URL "
            "templates, unscoped shell access, inline scripts. Metadata must "
            "carry `auto_generated: true` and `pending_review: true`.\n\n"
            "```yaml\n"
            f"{body}\n"
            "```\n"
        ),
        "priority": 5,
    }


def _preload_project_file_tree(domain_root: Path) -> dict[str, Any] | None:
    """Tier 1.5 — compact file-tree map for the domain's target code.

    Agents call `origin_fetch(path)` to read files from the origin source,
    but without a path map they have to guess. This preload injects a
    summary view of the project layout (top 2-3 levels, skipping obvious
    noise dirs) so the LLM has ground truth for what paths exist before
    it hits Tier 3.

    Walks `{domain_root}/src/` first, falls back to `{domain_root}` root
    if no src/. Respects common ignore patterns and hard-caps output size
    so we stay token-budget friendly.
    """
    # Candidate roots to scan, in preference order.
    candidates = [
        domain_root / "src",
        domain_root / "app",
        domain_root / "lib",
        domain_root,  # fallback
    ]
    target = next((c for c in candidates if c.is_dir()), None)
    if target is None:
        return None

    ignore_dirs = {
        ".git", ".venv", "venv", "env", "__pycache__", "node_modules",
        ".pytest_cache", ".mypy_cache", ".ruff_cache", "dist", "build",
        ".cache", ".gentcore", ".idea", ".vscode", "target", "coverage",
    }
    ignore_file_suffixes = {".pyc", ".pyo", ".so", ".o", ".a", ".dylib",
                            ".class", ".jar", ".lock", ".log"}

    # DFS walk so the rendered indent reflects parent-child structure
    # (BFS would intermix siblings across subtrees and look nested wrong).
    MAX_ENTRIES = 400
    MAX_DEPTH = 3

    entries: list[tuple[int, Path, bool]] = []  # (depth, path, is_dir)

    def _walk(cur: Path, depth: int) -> None:
        if len(entries) >= MAX_ENTRIES or depth > MAX_DEPTH:
            return
        try:
            children = sorted(cur.iterdir(), key=lambda p: (not p.is_dir(), p.name))
        except (OSError, PermissionError):
            return
        for child in children:
            if len(entries) >= MAX_ENTRIES:
                return
            name = child.name
            if name.startswith(".") and name not in (".github",):
                continue
            if child.is_dir():
                if name in ignore_dirs:
                    continue
                entries.append((depth, child, True))
                _walk(child, depth + 1)
            else:
                if any(name.endswith(suf) for suf in ignore_file_suffixes):
                    continue
                entries.append((depth, child, False))

    _walk(target, 1)

    if not entries:
        return None

    # Render as a compact indented tree relative to target.
    rel_target = target.relative_to(domain_root) if target != domain_root else Path(".")
    lines = [
        "# Project file tree (Tier 1.5 path map)",
        "",
        f"Root scanned: `{rel_target}/` (relative to domain).",
        "Use this to pick paths for `origin_fetch(path)` instead of "
        "guessing. For deeper browsing call `list_paths(prefix, depth)`.",
        "",
        f"```",
        f"{rel_target}/",
    ]
    truncated = len(entries) >= MAX_ENTRIES
    for depth, path, is_dir in entries:
        rel = path.relative_to(target)
        indent = "  " * depth
        marker = "/" if is_dir else ""
        lines.append(f"{indent}{rel.name}{marker}")
    if truncated:
        lines.append(f"... (truncated at {MAX_ENTRIES} entries — call `list_paths(prefix, depth)` to browse deeper)")
    lines.append("```")

    return {
        "source": "preload:project_file_tree",
        "content": "\n".join(lines),
        "priority": 6,  # between standards (10) and reference chunks (5)
    }


def _preload_domain_evolution_signals(domain_root: Path) -> dict[str, Any] | None:
    """Tier 5 — aggregate runtime audit trails for EvolutionAgent.

    Reads `.gentcore/origin_log.jsonl` + per-agent memory stores (and
    optional run records, which the runtime supplies post-hoc) and
    produces a single markdown bundle so the Evolution agent can
    consume pre-aggregated signals via preload instead of iterating
    file_read over a hundred JSONL files.
    """
    try:
        from harness.core.evolution_signals import gather_evolution_signals
    except Exception as exc:
        logger.warning("evolution_signals unavailable for preload: %s", exc)
        return None
    try:
        signals = gather_evolution_signals(domain_root)
    except Exception as exc:
        logger.warning("gather_evolution_signals failed for %s: %s", domain_root, exc)
        return None
    return {
        "source": "preload:domain_evolution_signals",
        "content": signals.format_markdown(),
        "priority": 6,
    }


def _preload_best_practice_library(domain_root: Path) -> dict[str, Any] | None:
    """Industry best-practice library preloaded for research/advisor agents.

    Reads the domain's `industry:` from `{domain_root}/domain.yaml`, loads
    the matching `config/best_practices/<industry>.yaml`, and renders it
    as markdown. BestPracticeResearchAgent consumes this to synthesize
    a knowledge_map in prompt-only mode; BestPracticeAdvisorAgent uses
    it to compute gaps against the generated standards.md.

    Returns None when:
      * domain.yaml is missing or has no `industry:` field
      * no curated library exists for that industry
    """
    domain_yaml = domain_root / "domain.yaml"
    if not domain_yaml.exists():
        return None
    try:
        cfg = yaml.safe_load(domain_yaml.read_text(encoding="utf-8")) or {}
    except Exception as exc:
        logger.warning("domain.yaml parse failed for best_practice_library: %s", exc)
        return None
    industry = str((cfg or {}).get("industry") or "").strip()
    if not industry:
        return None

    try:
        from harness.core.best_practices import load_library
    except Exception as exc:
        logger.warning("best_practices loader unavailable: %s", exc)
        return None
    lib = load_library(industry)
    if lib is None:
        return None

    # Render the library as markdown. Keep it compact so the preload
    # stays token-efficient even for libraries with 20+ principles.
    lines = [
        f"# Best-practice library: `{lib.industry}` (v{lib.version})",
        "",
    ]
    if lib.description:
        lines.append(lib.description.strip())
        lines.append("")
    lines.append(f"## Principles ({len(lib.principles)})")
    lines.append("")
    for p in lib.principles:
        lines.append(f"### `{p.id}` — {p.title}  ·  _{p.severity}_")
        if p.why:
            lines.append(f"**Why:** {p.why}")
        if p.must_have:
            lines.append("**Must-have markers:**")
            for m in p.must_have:
                lines.append(f"- {m}")
        if p.anti_patterns:
            lines.append("**Anti-patterns:**")
            for a in p.anti_patterns:
                lines.append(f"- {a}")
        if p.source_urls:
            lines.append("**References:** " + ", ".join(p.source_urls))
        lines.append("")
    if lib.anti_patterns:
        lines.append("## Cross-cutting anti-patterns")
        lines.append("")
        for a in lib.anti_patterns:
            lines.append(f"- {a}")
        lines.append("")
    if lib.canonical_sources:
        lines.append("## Canonical sources (for fetch_url research)")
        lines.append("")
        for s in lib.canonical_sources:
            lines.append(f"- {s}")

    return {
        "source": f"preload:best_practice_library:{lib.industry}",
        "content": "\n".join(lines),
        "priority": 7,
    }


def _preload_best_practices_overlay(domain_root: Path) -> dict[str, Any] | None:
    """Tier 1.5 — always-injected best-practice overlay.

    Reads `{domain_root}/context/best_practices.md` if present. The file is
    generated by `BestPracticeAdvisorAgent` during genesis and contains
    industry-standard guidance that the domain's own standards.md may be
    missing (gap analysis, not a replacement).

    Returns None when the file is absent — older domains that haven't
    been re-generated since the overlay feature landed get no overlay.
    Priority 9 sits it just below standards.md (10) and above Tier 2
    reference chunks (5), so the LLM sees it right after the always-
    injected baseline.
    """
    overlay = domain_root / "context" / "best_practices.md"
    if not overlay.exists():
        return None
    try:
        body = overlay.read_text(encoding="utf-8")
    except Exception as exc:
        logger.warning("best_practices_overlay read failed for %s: %s", overlay, exc)
        return None
    if not body.strip():
        return None
    return {
        "source": "preload:best_practices_overlay",
        "content": (
            "# Best-practice overlay (Tier 1.5)\n\n"
            "This is authoritative industry guidance that complements the "
            "domain's standards.md. Follow it when the two don't conflict.\n\n"
            f"{body}"
        ),
        "priority": 9,
    }


def _preload_domain_context_docs(domain_root: Path) -> dict[str, Any] | None:
    """Concatenate every *.md under {domain_root}/context/ into one blob."""
    ctx_dir = domain_root / "context"
    if not ctx_dir.exists():
        return None
    parts: list[str] = ["# Domain Context Documents (pre-loaded)\n\n"]
    files_found = False
    for md_path in sorted(ctx_dir.rglob("*.md")):
        try:
            body = md_path.read_text(encoding="utf-8")
        except Exception:
            continue
        rel = md_path.relative_to(domain_root)
        parts.append(f"## File: `{rel}`\n\n{body}\n\n---\n\n")
        files_found = True
    if not files_found:
        return None
    return {
        "source": "preload:domain_context_docs",
        "content": "".join(parts),
        "priority": 5,
    }


def _swap_architect_v1_to_v2(workflow: dict[str, Any]) -> dict[str, Any]:
    """Rewrite v1 Architect references to v2 when the feature flag is on.

    Operates on a shallow copy of the steps list so callers holding the
    original dict see the untouched version (defensive — the loader caches
    could be picked up by unaware readers).
    """
    if not _architect_v2_enabled():
        return workflow
    steps = workflow.get("steps") or []
    rewritten_any = False
    new_steps: list[Any] = []
    for step in steps:
        if isinstance(step, dict) and step.get("agent") == _ARCHITECT_V1_ID:
            new_step = {**step, "agent": _ARCHITECT_V2_ID}
            new_steps.append(new_step)
            rewritten_any = True
        else:
            new_steps.append(step)
    if rewritten_any:
        logger.info(
            "GENTCORE_ARCHITECT_V2=1 → swapped AgentArchitectAgent/v1 → v2 in workflow %r",
            workflow.get("name", "<unnamed>"),
        )
        return {**workflow, "steps": new_steps}
    return workflow


class ManifestLoader:
    """Loads YAML manifests and wires the framework into a runnable engine."""

    def __init__(self, packs_root: str | Path | None = None, registry: Any = None) -> None:
        # Optional override for tool pack YAML directory
        self._packs_root = Path(packs_root) if packs_root else None
        # H-REG: Optional shared AgentRegistry. When provided, build_step_configs
        # uses it to resolve agent directories in O(1) instead of scanning the
        # filesystem per step. Auto-created in boot_engine when omitted.
        self._registry = registry
        # Credential registry — populated during boot_engine; None until then.
        self._credential_registry: Any = None

    @property
    def credential_registry(self) -> Any:
        """The CredentialRegistry built during the last boot_engine call."""
        return self._credential_registry

    @staticmethod
    def resolve_required_credentials(
        agent_manifest: dict[str, Any],
        credential_registry: Any,
    ) -> list[Any]:
        """Derive the union set of credentials an agent needs from its declared tools.

        Called at agent-load time so a fresh agent-tools update applies without
        regenerating agent manifests. Builder keeps emitting only `tools: [...]`;
        this method makes `required_credentials` derived, not hand-authored.
        """
        return credential_registry.required_for_agent(agent_manifest)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def load_yaml(self, path: str | Path) -> dict[str, Any]:
        """Load any YAML file into a plain dict."""
        p = Path(path)
        return yaml.safe_load(p.read_text(encoding="utf-8")) or {}

    def load_domain(self, domain_path: str | Path) -> dict[str, Any]:
        """Load domain.yaml from a domain directory. Returns empty dict if not found."""
        p = Path(domain_path)
        yaml_file = p / "domain.yaml" if p.is_dir() else p
        if not yaml_file.exists():
            return {}
        data = self.load_yaml(yaml_file)
        try:
            from agent_contracts.manifests.domain_manifest import DomainManifest
            DomainManifest.model_validate(data)
        except Exception as exc:
            _emit_manifest_validation_failure("domain", yaml_file, exc)
        return data

    @staticmethod
    def load_industries(config_dir: str | Path | None = None) -> dict[str, dict[str, Any]]:
        """Load the industry registry from config/industries.yaml.

        Free-form industry strings on DomainManifest.industry are always allowed;
        this registry is consumed by the capability map (B2) to resolve stage_defaults.

        Args:
            config_dir: directory containing industries.yaml. Defaults to shadow-gentcore's
                        top-level config/ directory (project_root/config/).

        Returns:
            Dict of {industry_name: {description, typical_stages, typical_packs}}.
            Empty dict if the file is missing — callers must not hard-depend on it.
        """
        if config_dir is None:
            project_root = Path(__file__).resolve().parent.parent.parent
            config_dir = project_root / "config"
        registry_path = Path(config_dir) / "industries.yaml"
        if not registry_path.exists():
            return {}
        try:
            data = yaml.safe_load(registry_path.read_text(encoding="utf-8")) or {}
        except Exception as exc:
            logger.warning("Failed to parse industries.yaml at %s: %s", registry_path, exc)
            return {}
        industries = data.get("industries", {})
        return industries if isinstance(industries, dict) else {}

    def load_agent(
        self,
        agent_path: str | Path,
        domain_root: str | Path | None = None,
        domain_manifest: dict[str, Any] | None = None,
    ) -> tuple[dict[str, Any], str, list[dict[str, Any]]]:
        """Load an agent directory and return (manifest, system_prompt, context_items).

        Args:
            agent_path: Path to the agent version directory (e.g., agents/CodeGenAgent/v1/)
            domain_root: Root directory of the domain (for resolving context_files)
            domain_manifest: Already-loaded domain manifest (avoids re-reading)

        Returns:
            (manifest dict, system_prompt content, context_items list)
        """
        agent_dir = Path(agent_path)
        manifest = self.load_yaml(agent_dir / "agent_manifest.yaml")
        try:
            from agent_contracts.manifests.agent_manifest import AgentManifest
            AgentManifest.model_validate(manifest)
        except Exception as exc:
            _emit_manifest_validation_failure("agent", agent_dir, exc)

        # Resolve system_prompt_ref
        system_prompt = ""
        prompt_ref = manifest.get("system_prompt_ref", "system_prompt.md")
        prompt_path = agent_dir / prompt_ref
        if prompt_path.exists():
            system_prompt = prompt_path.read_text(encoding="utf-8")

        # Load domain context files (standards, architecture docs)
        context_items: list[dict[str, Any]] = []
        if domain_root and domain_manifest:
            context_items = self._load_context_files(
                Path(domain_root), domain_manifest.get("context_files", [])
            )

        # Auto-inject standards/glossary when agent manifest has context.inject_standards: true
        agent_ctx = manifest.get("context", {})
        if isinstance(agent_ctx, dict) and agent_ctx.get("inject_standards") and domain_root:
            dr = Path(domain_root)
            for ctx_key, default_path in [
                ("standards_path", "context/standards.md"),
                ("glossary_path", "context/glossary.md"),
            ]:
                ctx_path = dr / agent_ctx.get(ctx_key, default_path)
                if ctx_path.exists():
                    context_items.append({
                        "source": f"domain_context:{ctx_path.name}",
                        "content": ctx_path.read_text(encoding="utf-8"),
                        "priority": 10,
                    })

        # Pre-load bundled context sources declared in manifest.context.preload.
        # These convert tool-driven agents (react-mode fetching local catalogs)
        # into single-shot transform agents by baking the catalog into the
        # prompt upfront. Critical for vendors that hang on multi-turn tool_use
        # round-trips (MiniMax) and for eliminating 45-129min Layer 3 runs.
        preload_names = agent_ctx.get("preload") if isinstance(agent_ctx, dict) else None
        if preload_names:
            for preload_name in preload_names:
                item = _build_preload_item(preload_name, domain_root)
                if item:
                    context_items.append(item)

        # Load optional Python hooks referenced by hooks_ref field
        hooks: dict[str, Any] = {}
        hooks_ref = manifest.get("hooks_ref")
        if hooks_ref:
            hooks_path = agent_dir / hooks_ref
            if hooks_path.exists():
                import importlib.util
                spec = importlib.util.spec_from_file_location("agent_hooks", hooks_path)
                mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
                spec.loader.exec_module(mod)  # type: ignore[union-attr]
                for hook_name in ("pre_execute", "post_execute", "pre_tool_call"):
                    if hasattr(mod, hook_name):
                        hooks[hook_name] = getattr(mod, hook_name)
            else:
                logger.warning(
                    "hooks_ref '%s' specified in agent manifest at '%s' but file not found — hooks skipped",
                    hooks_ref,
                    agent_dir,
                )
        manifest["_hooks"] = hooks

        return manifest, system_prompt, context_items

    def load_workflow(self, workflow_path: str | Path) -> dict[str, Any]:
        """Load a workflow YAML file.

        B5 — when GENTCORE_ARCHITECT_V2=1, rewrites _genesis/AgentArchitectAgent/v1
        step references to v2 (catalog-driven architect). Rewrite happens
        after validation so the raw YAML still validates against the
        contract (both v1 and v2 are valid `agent` refs).
        """
        data = self.load_yaml(workflow_path)
        try:
            from agent_contracts.manifests.workflow_def import WorkflowDefinition
            WorkflowDefinition.model_validate(data)
        except Exception as exc:
            _emit_manifest_validation_failure("workflow", workflow_path, exc)
        return _swap_architect_v1_to_v2(data)

    def build_step_configs(
        self,
        workflow: dict[str, Any],
        domain_root: str | Path,
        domain_manifest: dict[str, Any],
        task_input: dict[str, Any] | None = None,
    ) -> dict[str, dict[str, Any]]:
        """Build step_configs dict for CompositionEngine from workflow + domain.

        Args:
            workflow: Loaded workflow dict
            domain_root: Root directory of the domain
            domain_manifest: Loaded domain manifest
            task_input: Optional initial task input injected into first step

        Returns:
            step_configs dict: {step_name: {manifest, task, system_prompt, context_items}}
        """
        domain_root = Path(domain_root)
        step_configs: dict[str, dict[str, Any]] = {}

        steps = workflow.get("steps", [])

        # H-REG: lazy-create a registry when the loader wasn't given one.
        # Shared registries (passed via constructor) benefit from previous
        # scans + path caches; loader-local ones still use the resolver
        # fallback chain, which subsumes the legacy 3-path logic.
        if self._registry is None:
            from harness.core.agent_registry import AgentRegistry
            self._registry = AgentRegistry()

        project_root = Path(__file__).resolve().parent.parent.parent

        for step in steps:
            # Support both "name" and "id" keys (domain agents use "id")
            step_name = step.get("name") or step.get("id", "")
            agent_id = step.get("agent", "")

            # H-REG: single-entry-point path resolution. Hits cache on
            # subsequent lookups; falls back to the 3-path scan on first miss.
            resolved = self._registry.resolve_path(agent_id, domain_root, project_root)
            agent_dir = resolved if resolved else domain_root / "agents" / agent_id

            # Load agent if directory exists
            manifest: dict[str, Any] = {}
            system_prompt = ""
            context_items: list[dict[str, Any]] = []

            if agent_dir.exists():
                manifest, system_prompt, context_items = self.load_agent(
                    agent_dir, domain_root, domain_manifest
                )
            else:
                # Fallback: just use agent_id as identifier
                manifest = {"id": agent_id}

            # Build task dict — task_input is available to ALL steps (not just first)
            # so every agent can access source paths, industry, domain_name, etc.
            task: dict[str, Any] = {"agent_id": agent_id, "step": step_name}
            if task_input:
                task.update(task_input)

            step_configs[step_name] = {
                "manifest": manifest,
                "task": task,
                "system_prompt": system_prompt,
                "context_items": context_items,
            }

        return step_configs

    def boot_engine(
        self,
        workflow_path: str | Path,
        domain_root: str | Path | None = None,
        provider: Any = None,
        task_input: dict[str, Any] | None = None,
    ) -> tuple[Any, dict[str, Any], dict[str, dict[str, Any]]]:
        """Boot a CompositionEngine from a workflow YAML file.

        Args:
            workflow_path: Path to workflow YAML
            domain_root: Domain root dir. Defaults to workflow's parent's parent.
            provider: LLM provider instance (optional, for real execution)
            task_input: Initial task input for first workflow step

        Returns:
            (engine, workflow_dict, step_configs) ready to call engine.execute_dag(steps, step_configs)
        """
        from harness.core.agent_runner import AgentRunner
        from harness.core.composition_engine import CompositionEngine
        from harness.core.tool_executor import ToolExecutor
        from harness.tools.builtin import register_builtins

        workflow_path = Path(workflow_path)
        workflow = self.load_workflow(workflow_path)

        # Infer domain root: workflow is at <domain_root>/workflows/<name>.yaml
        if domain_root is None:
            domain_root = workflow_path.parent.parent

        domain_root = Path(domain_root)
        domain_manifest = self.load_domain(domain_root)

        # Build rule engine (hot-reloadable from config/rules.yaml)
        from harness.core.rule_engine import RuleEngine
        rule_engine = RuleEngine()

        # Build tool executor with rule enforcement + built-in adapters + MCP servers
        tool_executor = ToolExecutor(rule_engine=rule_engine)
        register_builtins(tool_executor)

        # Resolve toolpack:// URIs from agent manifests and register HTTP adapters
        try:
            import agent_tools as _at
            _packs_root = self._packs_root or (Path(str(_at.__file__)).parent / "packs")
            resolver = _at.ToolResolver(pack_dirs=[_packs_root])
            # Collect all toolpack:// and tool:// URIs across workflow steps
            pack_uris: list[str] = []
            for step in workflow.get("steps", []):
                agent_id = step.get("agent", "")
                parts = agent_id.split("/")
                candidate_dir = None
                if len(parts) >= 2:
                    project_root = Path(__file__).resolve().parent.parent.parent
                    candidate_dir = project_root / "agents" / parts[0] / "/".join(parts[1:])
                if candidate_dir and (candidate_dir / "agent_manifest.yaml").exists():
                    amf = self.load_yaml(candidate_dir / "agent_manifest.yaml")
                    for tool in amf.get("tools", []):
                        pack_ref = (tool if isinstance(tool, str) else tool.get("pack", "")) or ""
                        if pack_ref.startswith("toolpack://") or pack_ref.startswith("tool://"):
                            pack_uris.append(pack_ref)
            # Register HTTP adapters for resolved packs + index into CredentialRegistry
            from harness.core.credential_registry import CredentialRegistry
            cred_registry = CredentialRegistry()
            registered_tool_names: list[str] = []
            for uri in set(pack_uris):
                pack = resolver.resolve_pack(uri) if uri.startswith("toolpack://") else None
                if pack is None:
                    continue
                # Index pack credentials into registry
                pack_yaml_path = getattr(pack, "_source_path", None)
                if pack_yaml_path and Path(pack_yaml_path).exists():
                    try:
                        pack_manifest = yaml.safe_load(Path(pack_yaml_path).read_text(encoding="utf-8")) or {}
                        cred_registry.register_tool_pack(pack_manifest)
                    except Exception as exc:
                        logger.debug("Failed to index credentials for pack %s: %s", uri, exc)
                for tool_uri in (pack.tools if hasattr(pack, "tools") else []):
                    tool_manifest = resolver.resolve_tool(tool_uri)
                    if tool_manifest and getattr(tool_manifest, "adapter_class", None) == "http_api":
                        adapter = _at.HTTPAPIToolAdapter(tool_manifest)
                        tool_name = tool_uri.replace("tool://", "")
                        tool_executor.register_adapter(tool_name, adapter)
                        registered_tool_names.append(tool_name)
            # Validate credentials — warn but don't block (additive, backward-compat)
            if registered_tool_names:
                report = cred_registry.validate(registered_tool_names)
                if report.missing:
                    missing_names = ", ".join(r.name for r in report.missing)
                    logger.warning(
                        "Missing credentials for registered tools: %s — "
                        "set them via export or ~/.gentcore/credentials.json",
                        missing_names,
                    )
                else:
                    logger.debug("All tool credentials resolved (%d tools checked)", len(registered_tool_names))
            self._credential_registry = cred_registry
        except Exception as exc:
            logger.debug("agent-tools integration unavailable, skipping toolpack registration: %s", exc)

        # Register MCP server tools from config/mcp_servers.yaml
        try:
            from harness.tools.mcp_loader import register_mcp_tools
            register_mcp_tools(tool_executor)
        except Exception as exc:
            logger.debug("MCP tools registration skipped (config missing or unavailable): %s", exc)

        # Build AgentRunner with persistent per-domain memory. Tier 4 —
        # AgentRunner auto-injects the last N run_outputs as context and
        # records each new completed run when memory_store is wired in.
        memory_store = build_memory_store(Path(domain_root))
        runner = AgentRunner(
            provider=provider,
            tool_executor=tool_executor,
            memory_store=memory_store,
        )

        # Build output validator for post-execution quality checks
        from harness.core.output_validator import OutputValidator
        output_validator = OutputValidator()

        # Build CompositionEngine
        engine = CompositionEngine(agent_runner=runner, output_validator=output_validator)

        # Register feedback loops from workflow definition
        for loop_def in workflow.get("feedback_loops", []):
            from harness.core.feedback_loop import FeedbackLoop
            max_iter = loop_def.get("max_iterations") or loop_def.get("max_rounds", 2)
            condition_expr = loop_def.get("condition")
            if condition_expr:
                condition_fn = lambda result, _c=condition_expr: not engine._evaluate_condition(_c, result)
            else:
                condition_fn = None
            loop = FeedbackLoop(
                from_step=loop_def.get("from_step", ""),
                to_step=loop_def.get("to_step", ""),
                condition_fn=condition_fn,
                max_iterations=max_iter,
            )
            engine.register_feedback_loop(loop)

        # Build step configs
        step_configs = self.build_step_configs(
            workflow, domain_root, domain_manifest, task_input
        )

        return engine, workflow, step_configs

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_context_files(
        self, domain_root: Path, context_file_refs: list[str]
    ) -> list[dict[str, Any]]:
        """Load domain context files and return as context_items."""
        items: list[dict[str, Any]] = []
        for ref in context_file_refs:
            path = domain_root / ref
            if path.exists():
                content = path.read_text(encoding="utf-8")
                items.append({
                    "source": f"domain_context:{path.name}",
                    "content": content,
                    "priority": 10,  # High priority — standards stay in context
                })
        return items
