#!/usr/bin/env python3
"""End-to-end genesis pipeline — direct claude -p bypass.

Bypasses harness/AgentRunner entirely. Each step calls `claude -p` directly
via asyncio subprocess, so native Write/Bash tools work inside claude and
file writes actually land on disk.

Usage:
    .venv/bin/python scripts/run_genesis_e2e.py
"""

import asyncio
import os
import re
import time
import textwrap
from pathlib import Path

# ── Constants ──────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
SAMPLE_PROJECT = ROOT / "sample_project"
DOMAIN_OUTPUT = ROOT / "domain-fullstack"
STEPS_DIR = ROOT / ".genesis_steps"


# ── Core helper ────────────────────────────────────────────────────────────

async def run_claude(prompt: str, name: str, timeout: int = 900, max_turns: int = 30) -> str:
    """Run claude -p and return output. Prints real-time progress."""
    print(f"  [{name}] Sending to claude-p ({len(prompt)} chars)...", flush=True)

    cmd = ["claude", "-p", "--max-turns", str(max_turns), "--dangerously-skip-permissions"]
    env = {k: v for k, v in os.environ.items() if k != "ANTHROPIC_API_KEY"}

    if len(prompt) > 40000:
        prompt = prompt[:40000] + "\n\n[Context truncated. Produce your final output now.]"

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )
        start = time.time()
        stdout, stderr = await asyncio.wait_for(
            proc.communicate(input=prompt.encode("utf-8")), timeout=timeout
        )
        elapsed = time.time() - start
        out = stdout.decode("utf-8", errors="replace").strip()
        if proc.returncode != 0 and not out:
            err = stderr.decode("utf-8", errors="replace").strip()
            if err:
                out = f"Error: {err}"
        print(f"  [{name}] Done in {elapsed:.1f}s ({len(out)} chars)", flush=True)
        return out
    except asyncio.TimeoutError:
        print(f"  [{name}] TIMEOUT after {timeout}s", flush=True)
        return f"Error: Timeout after {timeout}s"
    except Exception as e:
        print(f"  [{name}] FAILED: {e}", flush=True)
        return f"Error: {e}"


# ── Step summary printer ───────────────────────────────────────────────────

def print_step_summary(num: int, name: str, output: str, elapsed: float) -> None:
    status = "ERROR" if output.startswith("Error:") else "OK"
    preview = output[:200].replace("\n", " ")
    print(f"  [{name}] Step {num} {status} in {elapsed:.1f}s — preview: {preview!r}", flush=True)


# ── File extraction fallback ───────────────────────────────────────────────

def extract_and_write_files(content: str, base_dir: Path) -> list[str]:
    """Parse agent output and write any embedded file contents to disk."""
    written: list[str] = []

    # Pattern 1: ### FILE: path/to/file\n```lang\ncontent\n```
    pattern1 = re.compile(r"###\s+FILE:\s+([^\n]+)\n```[^\n]*\n(.*?)\n```", re.DOTALL)
    # Pattern 2: ## path/to/file (when path contains / or extension)
    pattern2 = re.compile(
        r"##\s+([\w/.-]+\.(?:yaml|md|json|py|txt))\n```[^\n]*\n(.*?)\n```", re.DOTALL
    )
    # Pattern 3: **path/to/file** code block
    pattern3 = re.compile(
        r"\*\*([\w/.-]+\.(?:yaml|md|json|py|txt))\*\*\s*\n```[^\n]*\n(.*?)\n```", re.DOTALL
    )

    for pattern in [pattern1, pattern2, pattern3]:
        for m in pattern.finditer(content):
            rel_path = m.group(1).strip()
            file_content = m.group(2)
            full_path = base_dir / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(file_content)
            written.append(str(rel_path))
            print(f"  [Extracted] {rel_path}", flush=True)

    return written


# ── Minimal domain fallback ────────────────────────────────────────────────

def write_minimal_domain(
    architect_output: str,
    context_output: str,
    scan_output: str,
    base_dir: Path,
) -> None:
    """Write a minimal but valid domain structure from whatever data is available."""
    _ = architect_output  # reserved for future extraction logic
    base_dir.mkdir(parents=True, exist_ok=True)

    # domain.yaml
    domain_yaml = textwrap.dedent("""\
        name: fullstack
        version: "1.0"
        description: Full-stack domain generated by genesis pipeline
        domains:
          - backend
          - frontend
          - infra
        context:
          standards: context/standards.md
          glossary: context/glossary.md
        agents_dir: agents
        workflows_dir: workflows
    """)
    (base_dir / "domain.yaml").write_text(domain_yaml)
    print("  [Fallback] Wrote domain.yaml", flush=True)

    # context/standards.md — try to extract from context step, else from scan
    standards_content = _extract_standards(context_output, scan_output)
    ctx_dir = base_dir / "context"
    ctx_dir.mkdir(exist_ok=True)
    (ctx_dir / "standards.md").write_text(standards_content)
    print("  [Fallback] Wrote context/standards.md", flush=True)

    # context/glossary.md
    glossary = textwrap.dedent("""\
        # Glossary

        | Term | Definition |
        |------|-----------|
        | Agent | A YAML manifest + system prompt that performs a scoped task |
        | Domain | A bounded context with agents, context docs, and workflows |
        | Workflow | Ordered execution plan for a set of agents |
        | Genesis | The pipeline that auto-generates domain repos |
    """)
    (ctx_dir / "glossary.md").write_text(glossary)
    print("  [Fallback] Wrote context/glossary.md", flush=True)

    # agents/BackendAgent/v1/
    backend_dir = base_dir / "agents" / "BackendAgent" / "v1"
    backend_dir.mkdir(parents=True, exist_ok=True)
    manifest = textwrap.dedent("""\
        agent_id: BackendAgent/v1
        name: BackendAgent
        version: "1"
        purpose: >
          Handle backend API development tasks including REST endpoints,
          database models, authentication, and service layer logic.
        execution_mode: react
        tools:
          - file_read
          - file_write
          - bash
          - search_code
        context:
          inject_standards: true
          reference_docs:
            - context/standards.md
        constraints:
          max_tokens: 8192
          timeout_seconds: 300
    """)
    (backend_dir / "agent_manifest.yaml").write_text(manifest)
    (backend_dir / "system_prompt.md").write_text(textwrap.dedent("""\
        # BackendAgent

        You are a senior backend engineer. Your responsibilities:
        - Design and implement REST APIs following project standards
        - Write database models with proper relationships
        - Implement authentication and authorization
        - Write unit and integration tests
        - Follow the standards defined in context/standards.md

        ## Guidelines
        - Always validate inputs
        - Handle errors with descriptive messages
        - Document public interfaces with docstrings
        - Write tests for every endpoint and service method
    """))
    print("  [Fallback] Wrote agents/BackendAgent/v1/", flush=True)

    # agents/FrontendAgent/v1/
    frontend_dir = base_dir / "agents" / "FrontendAgent" / "v1"
    frontend_dir.mkdir(parents=True, exist_ok=True)
    (frontend_dir / "agent_manifest.yaml").write_text(textwrap.dedent("""\
        agent_id: FrontendAgent/v1
        name: FrontendAgent
        version: "1"
        purpose: >
          Handle frontend development tasks including React components,
          state management, API integration, and UI/UX implementation.
        execution_mode: react
        tools:
          - file_read
          - file_write
          - bash
        context:
          inject_standards: true
          reference_docs:
            - context/standards.md
        constraints:
          max_tokens: 8192
          timeout_seconds: 300
    """))
    (frontend_dir / "system_prompt.md").write_text(textwrap.dedent("""\
        # FrontendAgent

        You are a senior frontend engineer. Your responsibilities:
        - Build React components following project conventions
        - Manage application state with appropriate patterns
        - Integrate with backend APIs
        - Ensure accessibility and responsive design
        - Write component tests

        ## Guidelines
        - Prefer functional components with hooks
        - Keep components small and focused
        - Use TypeScript types for all props and state
        - Write snapshot and interaction tests
    """))
    print("  [Fallback] Wrote agents/FrontendAgent/v1/", flush=True)

    # workflows/main.yaml
    wf_dir = base_dir / "workflows"
    wf_dir.mkdir(exist_ok=True)
    (wf_dir / "main.yaml").write_text(textwrap.dedent("""\
        name: main
        version: "1.0"
        description: Main fullstack development workflow
        steps:
          - id: backend
            agent: BackendAgent/v1
            description: Implement backend changes
            inputs:
              - task
          - id: frontend
            agent: FrontendAgent/v1
            description: Implement frontend changes
            depends_on:
              - backend
            inputs:
              - task
              - backend_output: "{{steps.backend.output}}"
    """))
    print("  [Fallback] Wrote workflows/main.yaml", flush=True)


def _extract_standards(context_output: str, scan_output: str) -> str:
    """Extract standards content from context engineer or scan output."""
    # Try to find a standards section in context output
    for source in [context_output, scan_output]:
        if not source:
            continue
        # Look for a standards block
        m = re.search(
            r"(?:standards\.md|# Standards|## Standards)(.*?)(?:###|## [A-Z]|\Z)",
            source,
            re.DOTALL | re.IGNORECASE,
        )
        if m:
            extracted = m.group(1).strip()
            if len(extracted) > 100:
                return f"# Project Standards\n\n{extracted[:4000]}"

    # Generic fallback
    return textwrap.dedent("""\
        # Project Standards

        ## Code Quality
        - All code must pass linting before merge
        - Functions must have docstrings/JSDoc
        - Test coverage must exceed 80%

        ## Git Workflow
        - Feature branches from main
        - Pull requests required for all changes
        - Squash merge to main

        ## API Design
        - RESTful conventions
        - Versioned endpoints (/api/v1/...)
        - JSON request/response bodies
        - Standard error format: {error, message, code}

        ## Backend
        - Input validation on all endpoints
        - Structured logging
        - Environment-based configuration

        ## Frontend
        - TypeScript strict mode
        - Component-level tests
        - Accessible markup (WCAG 2.1 AA)
    """)


# ── Prompt builders ────────────────────────────────────────────────────────

def build_scanner_prompt() -> str:
    sample = str(SAMPLE_PROJECT)
    return textwrap.dedent(f"""\
        You are SourceScannerAgent. Scan the sample project at: {sample}

        Use your Bash tool to:
        1. List all files: `find {sample} -type f | head -100`
        2. Read key config files (package.json, requirements.txt, pyproject.toml, Makefile, README.md, etc.)
        3. Read 2-3 representative source files from backend/, frontend/, and infra/ subdirectories
        4. Read any docs/ files if present

        Then output a structured JSON object (no extra text, just the JSON) with this exact shape:
        {{
          "scan_summary": "one paragraph describing what you found",
          "reference_scan": {{
            "standards_extracted": ["list of standards/conventions found"],
            "key_files": ["list of important file paths you read"]
          }},
          "target_scan": {{
            "backend": {{"language": "...", "framework": "...", "key_patterns": [...]}},
            "frontend": {{"language": "...", "framework": "...", "key_patterns": [...]}},
            "infra": {{"tools": [...], "key_patterns": [...]}}
          }},
          "domains_detected": ["backend", "frontend", "infra"],
          "scan_quality": {{
            "overall_coverage": 0.85,
            "backend_coverage": 0.9,
            "frontend_coverage": 0.8,
            "infra_coverage": 0.8
          }}
        }}

        Keep the JSON under 8000 characters. Be precise and factual — only report what you actually found.
    """)


def build_mapper_prompt(scan: str) -> str:
    return textwrap.dedent(f"""\
        You are KnowledgeMapperAgent. Classify and map knowledge from this source scan.

        ## Source Scanner Output
        {scan[:6000]}

        Analyze the scan and produce a JSON knowledge_map with this shape:
        {{
          "categories": {{
            "architecture": ["list of architectural patterns/decisions found"],
            "testing": ["testing conventions and tools"],
            "style": ["code style rules and linting config"],
            "deployment": ["CI/CD and deployment patterns"],
            "security": ["auth/security patterns"]
          }},
          "coverage_scores": {{
            "backend": 0.85,
            "frontend": 0.80,
            "infra": 0.75,
            "overall": 0.80
          }},
          "standards_sources": [
            {{"standard": "description", "content_ref": "file or section where found"}}
          ],
          "missing_domains": ["list of domains not well covered"],
          "priority_gaps": ["top 3 gaps to address in context docs"]
        }}

        Output only the JSON object. Under 6000 characters.
    """)


def build_context_prompt(scan: str, map_: str) -> str:
    sample = str(SAMPLE_PROJECT)
    return textwrap.dedent(f"""\
        You are ContextEngineerAgent. Generate context documents for the domain.

        ## Source Scanner Output
        {scan[:3000]}

        ## Knowledge Map
        {map_[:3000]}

        Use your Bash or Read tool to read 2-3 key source files from {sample} that
        were identified as containing standards (check the key_files in the scanner output).

        Then generate these documents. Output each in a clearly labeled code block:

        ### FILE: context/standards.md
        ```markdown
        [full standards document, under 400 lines, based on what you actually found]
        ```

        ### FILE: context/glossary.md
        ```markdown
        [glossary of domain terms in a markdown table]
        ```

        ### FILE: context/reference/backend_patterns.md
        ```markdown
        [backend patterns reference doc]
        ```

        ### FILE: context/reference/frontend_patterns.md
        ```markdown
        [frontend patterns reference doc]
        ```

        Use the ### FILE: prefix exactly as shown. Each block must be a complete document.
        Base content on the actual project — do not invent standards not present in the source.
    """)


def build_architect_prompt(scan: str, map_: str, ctx: str) -> str:
    return textwrap.dedent(f"""\
        You are AgentArchitectAgent. Design the domain agent roster.

        ## Source Scanner Output
        {scan[:2000]}

        ## Knowledge Map
        {map_[:2000]}

        ## Context Documents Generated
        {ctx[:2000]}

        Design the agents for this domain. Output JSON:
        {{
          "agent_roster": [
            {{
              "name": "BackendAgent",
              "purpose": "Handle backend API, models, and service layer",
              "tools": ["file_read", "file_write", "bash", "search_code"],
              "execution_mode": "react",
              "key_responsibilities": ["REST endpoints", "database models", "auth"]
            }},
            {{
              "name": "FrontendAgent",
              "purpose": "Handle React components, state, and API integration",
              "tools": ["file_read", "file_write", "bash"],
              "execution_mode": "react",
              "key_responsibilities": ["components", "state management", "API calls"]
            }},
            {{
              "name": "InfraAgent",
              "purpose": "Handle CI/CD, Docker, and deployment configuration",
              "tools": ["file_read", "file_write", "bash"],
              "execution_mode": "plan_execute",
              "key_responsibilities": ["docker", "ci-cd", "env config"]
            }},
            {{
              "name": "ReviewerAgent",
              "purpose": "Review PRs and enforce standards",
              "tools": ["file_read", "bash"],
              "execution_mode": "react",
              "key_responsibilities": ["code review", "standards enforcement"]
            }}
          ],
          "workflow_design": {{
            "name": "main",
            "steps": [
              {{"id": "backend", "agent": "BackendAgent", "description": "Implement backend changes"}},
              {{"id": "frontend", "agent": "FrontendAgent", "depends_on": ["backend"]}},
              {{"id": "review", "agent": "ReviewerAgent", "depends_on": ["backend", "frontend"]}}
            ]
          }}
        }}

        Output only the JSON. Be precise about tool names and execution modes.
    """)


def build_builder_prompt(scan: str, map_: str, ctx: str, arch: str) -> str:
    _ = (scan, map_)  # available for future context injection
    output = str(DOMAIN_OUTPUT)
    return textwrap.dedent(f"""\
        You are AgentBuilderAgent. Your job is to write the domain agent files to disk.

        ## Target Output Directory
        {output}

        ## Agent Architecture
        {arch[:4000]}

        ## Context Documents (use this exact content for context files)
        {ctx[:5000]}

        ## Instructions — YOU MUST WRITE FILES TO DISK

        You MUST use your Bash tool or Write tool to create ALL the files below.
        Do NOT just output text — actually write the files using Bash or Write tool calls.

        Step 1: Create directories
        ```bash
        mkdir -p {output}/context/reference
        mkdir -p {output}/agents/BackendAgent/v1
        mkdir -p {output}/agents/FrontendAgent/v1
        mkdir -p {output}/agents/InfraAgent/v1
        mkdir -p {output}/agents/ReviewerAgent/v1
        mkdir -p {output}/workflows
        ```

        Step 2: Write each file using the Write tool or bash heredoc.

        Required files:
        1. {output}/domain.yaml — domain manifest with name, version, description, domains list, context paths
        2. {output}/context/standards.md — copy from the Context Documents above (the standards.md content)
        3. {output}/context/glossary.md — copy from the Context Documents above (the glossary.md content)
        4. {output}/agents/BackendAgent/v1/agent_manifest.yaml — YAML manifest with agent_id, name, purpose, tools, execution_mode, constraints
        5. {output}/agents/BackendAgent/v1/system_prompt.md — system prompt for BackendAgent
        6. {output}/agents/FrontendAgent/v1/agent_manifest.yaml
        7. {output}/agents/FrontendAgent/v1/system_prompt.md
        8. {output}/agents/InfraAgent/v1/agent_manifest.yaml
        9. {output}/agents/InfraAgent/v1/system_prompt.md
        10. {output}/workflows/main.yaml — workflow YAML with the steps from the architecture

        Step 3: After writing, verify by running:
        ```bash
        find {output} -type f | sort
        ```

        Write real content based on the architecture and context above.
        For domain.yaml use this structure:
          name: fullstack
          version: "1.0"
          description: <from scan>
          domains: [backend, frontend, infra]
          context:
            standards: context/standards.md
          agents_dir: agents
          workflows_dir: workflows

        For agent manifests use:
          agent_id: <Name>/v1
          name: <Name>
          version: "1"
          purpose: <from architecture>
          execution_mode: react
          tools: [file_read, file_write, bash]
          context:
            inject_standards: true
          constraints:
            max_tokens: 8192
            timeout_seconds: 300

        YOU MUST ACTUALLY WRITE THE FILES — do not just describe what you would write.
        Use Write tool or Bash heredoc for each file. Confirm with the find command at the end.
    """)


def build_quality_prompt() -> str:
    output = str(DOMAIN_OUTPUT)
    return textwrap.dedent(f"""\
        You are QualityGateAgent. Inspect the generated domain at: {output}

        Use your Bash tool to:
        1. List all files: `find {output} -type f | sort`
        2. Read domain.yaml
        3. Read context/standards.md (first 50 lines)
        4. Read one agent manifest (e.g. agents/BackendAgent/v1/agent_manifest.yaml)
        5. Read workflows/main.yaml

        Then output a quality report as JSON:
        {{
          "files_found": ["list of files you found"],
          "missing_required": ["list of required files that are missing"],
          "score": 85,
          "issues": ["list of quality issues found"],
          "domain_yaml_valid": true,
          "standards_present": true,
          "agents_count": 3,
          "workflows_count": 1,
          "summary": "one sentence summary of quality"
        }}

        Required files for a passing score (>=70):
        - domain.yaml
        - context/standards.md
        - agents/BackendAgent/v1/agent_manifest.yaml
        - agents/BackendAgent/v1/system_prompt.md
        - workflows/main.yaml

        Score 100 if all required files present with valid content.
        Deduct 15 points per missing required file.
        Output only the JSON.
    """)


# ── Main ───────────────────────────────────────────────────────────────────

async def main() -> None:
    start_total = time.time()
    STEPS_DIR.mkdir(exist_ok=True)

    print("=" * 70, flush=True)
    print("GENESIS E2E PIPELINE — DIRECT claude -p", flush=True)
    print(f"Source: {SAMPLE_PROJECT}", flush=True)
    print(f"Output: {DOMAIN_OUTPUT}", flush=True)
    print(f"Steps:  {STEPS_DIR}", flush=True)
    print("=" * 70, flush=True)

    results: dict[str, str] = {}

    def trunc(s: str, n: int = 6000) -> str:
        return s[:n] if len(s) > n else s

    # ── Step 1: SourceScanner ──────────────────────────────────────────────
    print("\n--- STEP 1: SourceScanner ---", flush=True)
    t = time.time()
    r1 = await run_claude(build_scanner_prompt(), "SourceScanner", timeout=600)
    results["scan"] = r1
    (STEPS_DIR / "step1_scan.txt").write_text(r1)
    print_step_summary(1, "SourceScanner", r1, time.time() - t)

    if r1.startswith("Error:"):
        print("  [RETRY] Step 1 failed, retrying once...", flush=True)
        r1 = await run_claude(build_scanner_prompt(), "SourceScanner", timeout=600)
        results["scan"] = r1
        (STEPS_DIR / "step1_scan_retry.txt").write_text(r1)

    # ── Step 2: KnowledgeMapper ────────────────────────────────────────────
    print("\n--- STEP 2: KnowledgeMapper ---", flush=True)
    t = time.time()
    r2 = await run_claude(build_mapper_prompt(trunc(r1)), "KnowledgeMapper", timeout=600)
    results["map"] = r2
    (STEPS_DIR / "step2_map.txt").write_text(r2)
    print_step_summary(2, "KnowledgeMapper", r2, time.time() - t)

    if r2.startswith("Error:"):
        print("  [RETRY] Step 2 failed, retrying once...", flush=True)
        r2 = await run_claude(build_mapper_prompt(trunc(r1)), "KnowledgeMapper", timeout=600)
        results["map"] = r2
        (STEPS_DIR / "step2_map_retry.txt").write_text(r2)

    # ── Step 3: ContextEngineer ────────────────────────────────────────────
    print("\n--- STEP 3: ContextEngineer ---", flush=True)
    t = time.time()
    r3 = await run_claude(
        build_context_prompt(trunc(r1, 3000), trunc(r2, 3000)),
        "ContextEngineer",
        timeout=600,
    )
    results["ctx"] = r3
    (STEPS_DIR / "step3_ctx.txt").write_text(r3)
    print_step_summary(3, "ContextEngineer", r3, time.time() - t)

    if r3.startswith("Error:"):
        print("  [RETRY] Step 3 failed, retrying once...", flush=True)
        r3 = await run_claude(
            build_context_prompt(trunc(r1, 3000), trunc(r2, 3000)),
            "ContextEngineer",
            timeout=600,
        )
        results["ctx"] = r3
        (STEPS_DIR / "step3_ctx_retry.txt").write_text(r3)

    # ── Step 4: AgentArchitect ─────────────────────────────────────────────
    print("\n--- STEP 4: AgentArchitect ---", flush=True)
    t = time.time()
    r4 = await run_claude(
        build_architect_prompt(trunc(r1, 2000), trunc(r2, 2000), trunc(r3, 2000)),
        "AgentArchitect",
        timeout=600,
    )
    results["arch"] = r4
    (STEPS_DIR / "step4_arch.txt").write_text(r4)
    print_step_summary(4, "AgentArchitect", r4, time.time() - t)

    if r4.startswith("Error:"):
        print("  [RETRY] Step 4 failed, retrying once...", flush=True)
        r4 = await run_claude(
            build_architect_prompt(trunc(r1, 2000), trunc(r2, 2000), trunc(r3, 2000)),
            "AgentArchitect",
            timeout=600,
        )
        results["arch"] = r4
        (STEPS_DIR / "step4_arch_retry.txt").write_text(r4)

    # ── Step 5: AgentBuilder ───────────────────────────────────────────────
    print("\n--- STEP 5: AgentBuilder (writes files to disk) ---", flush=True)
    t = time.time()
    r5 = await run_claude(
        build_builder_prompt(
            trunc(r1, 2000),
            trunc(r2, 2000),
            trunc(r3, 5000),
            trunc(r4, 4000),
        ),
        "AgentBuilder",
        timeout=900,
        max_turns=30,
    )
    results["build"] = r5
    (STEPS_DIR / "step5_build.txt").write_text(r5)
    print_step_summary(5, "AgentBuilder", r5, time.time() - t)

    if r5.startswith("Error:"):
        print("  [RETRY] Step 5 failed, retrying once...", flush=True)
        r5 = await run_claude(
            build_builder_prompt(
                trunc(r1, 2000),
                trunc(r2, 2000),
                trunc(r3, 5000),
                trunc(r4, 4000),
            ),
            "AgentBuilder",
            timeout=900,
            max_turns=30,
        )
        results["build"] = r5
        (STEPS_DIR / "step5_build_retry.txt").write_text(r5)

    # ── After Step 5: check if files were actually written ─────────────────
    domain_yamls = list(DOMAIN_OUTPUT.rglob("*.yaml")) if DOMAIN_OUTPUT.exists() else []
    if not domain_yamls:
        print(
            "\n  [Builder] claude didn't write files directly — extracting from output...",
            flush=True,
        )
        written = extract_and_write_files(results.get("build", ""), DOMAIN_OUTPUT)
        if not written:
            print(
                "  [Builder] Extraction found no file blocks — also trying context step output...",
                flush=True,
            )
            written += extract_and_write_files(results.get("ctx", ""), DOMAIN_OUTPUT)

        if not written:
            print(
                "  [Builder] No files extracted — writing minimal domain structure from step data...",
                flush=True,
            )
            write_minimal_domain(
                architect_output=results.get("arch", ""),
                context_output=results.get("ctx", ""),
                scan_output=results.get("scan", ""),
                base_dir=DOMAIN_OUTPUT,
            )
        else:
            # Even with some files extracted, ensure domain.yaml exists
            if not (DOMAIN_OUTPUT / "domain.yaml").exists():
                write_minimal_domain(
                    architect_output=results.get("arch", ""),
                    context_output=results.get("ctx", ""),
                    scan_output=results.get("scan", ""),
                    base_dir=DOMAIN_OUTPUT,
                )

    # ── Step 6: QualityGate ────────────────────────────────────────────────
    print("\n--- STEP 6: QualityGate ---", flush=True)
    t = time.time()
    r6 = await run_claude(build_quality_prompt(), "QualityGate", timeout=300, max_turns=10)
    results["quality"] = r6
    (STEPS_DIR / "step6_quality.txt").write_text(r6)
    print_step_summary(6, "QualityGate", r6, time.time() - t)

    # ── Final summary ──────────────────────────────────────────────────────
    total_time = time.time() - start_total

    print(f"\n{'=' * 70}", flush=True)
    print("COMPLETE", flush=True)
    print(f"Duration: {total_time:.1f}s", flush=True)
    print(f"Steps dir: {STEPS_DIR}", flush=True)

    if DOMAIN_OUTPUT.exists():
        files = [f for f in DOMAIN_OUTPUT.rglob("*") if f.is_file()]
        print(f"Domain files: {len(files)}", flush=True)
        for f in sorted(files):
            size = f.stat().st_size
            print(f"  {f.relative_to(DOMAIN_OUTPUT)}  ({size} bytes)", flush=True)
    else:
        print("Domain output dir not created.", flush=True)

    # Print quality score if parseable
    try:
        import json
        q = json.loads(r6)
        print(f"\nQuality score: {q.get('score', 'N/A')}/100", flush=True)
        if q.get("issues"):
            print("Issues:", flush=True)
            for issue in q["issues"]:
                print(f"  - {issue}", flush=True)
        if q.get("missing_required"):
            print("Missing files:", flush=True)
            for f in q["missing_required"]:
                print(f"  - {f}", flush=True)
    except Exception:
        pass

    print(f"{'=' * 70}", flush=True)


if __name__ == "__main__":
    asyncio.run(main())
